### ISSUE TITLE
Automatically generate config.yml using information from instances.yml 

### ISSUE THREAD

**Issue by s-ocando** [wazuh/wazuh-packages#1045]
For a better user experience using the [unattended_installation.sh](https://github.com/wazuh/wazuh-packages/blob/unify-unattended/unattended_scripts/unattended_installation.sh) for distributed installations, use the information contained in [instances.yml](https://github.com/wazuh/wazuh-packages/blob/unify-unattended/unattended_scripts/instances.yml) to automatically populate [config.yml](https://github.com/wazuh/wazuh-packages/blob/unify-unattended/unattended_scripts/config.yml). 

This will simplify the steps that the user must do and avoid having to enter repeated information.

instances.yml: 

```
# Elasticsearch nodes
elasticsearch-nodes:
  - name: node1
    ip:
      - 172.16.1.17
  - name: node2
    ip:
      - 172.16.1.64
  - name: node3
    ip:
      - 172.16.1.65

# Wazuh server nodes
wazuh-servers:
  - name: wazuh1
    ip:
      - 172.16.1.17  

# Kibana node
kibana:
  - name: kibana
    ip:
      - 172.16.1.17
```

config.yml:
```
## Multi-node configuration

## Elasticsearch configuration

cluster.name: wazuh

cluster.initial_master_nodes:
        - node1
        - node2
        - node3

discovery.seed_hosts:
        - 172.16.1.17
        - 172.16.1.64
        - 172.16.1.65

## Certificates creation

# Clients certificates
clients:
  - name: admin
    dn: CN=admin,OU=Docu,O=Wazuh,L=California,C=US
    admin: true
  - name: filebeat
    dn: CN=filebeat,OU=Docu,O=Wazuh,L=California,C=US


# Kibana-instance
- 172.16.1.17

# Wazuh-master-configuration
- 172.16.1.17 
```
