### ISSUE TITLE
Add permissions to wazuh_ui roles and make roles_mapping editable

### ISSUE THREAD

**Issue by fhielpos** [wazuh/wazuh-packages#1059]
|Wazuh version|Install type|Action performed|Platform|
|---|---|---|---|
| X.Y.Z-rev | Opendistro Security | Install | OS version |

Hello team,

Right now, the `wazuh_ui_*` roles are only used by `wazuh_user` and `wazuh_admin` and they can not be assigned to any other users as the `roles_mapping` are `reserved`.

**roles.yml**
https://github.com/wazuh/wazuh-packages/blob/5adcf8a6c74cb7184223a92a789d06fd0f2e89af/unattended_scripts/open-distro/elasticsearch/roles/roles.yml#L132:L163

**roles_mapping.yml**
https://github.com/wazuh/wazuh-packages/blob/5adcf8a6c74cb7184223a92a789d06fd0f2e89af/unattended_scripts/open-distro/elasticsearch/roles/roles_mapping.yml#L55:L72

Also, these roles are missing access to `.kibana` indices as well as to the `global_tenant` causing the roles to lack permissions to access the UI without assigning more roles.

## Description

To simplify the `roles` assignment, we could add the missing permissions to the `roles.yml` file as follows:

```yaml
wazuh_ui_user:
  reserved: true
  hidden: false
  cluster_permissions: []
  index_permissions:
  - index_patterns:
    - "wazuh-*"
    - ".kibana*"
    dls: ""
    fls: []
  masked_fields: []
    allowed_actions:
    - "read"
  tenant_permissions:
  - tenant_patterns:
    - "global_tenant"
    allowed_actions:
    - "kibana_all_read"
  static: false
wazuh_ui_admin:
  reserved: true
  hidden: false
  cluster_permissions: []
  index_permissions:
  - index_patterns:
    - "wazuh-*"
    - ".kibana*"
    dls: ""
    fls: []
    masked_fields: []
    allowed_actions:
    - "read"
    - "delete"
    - "manage"
    - "index"
  tenant_permissions:
  - tenant_patterns:
    - "global_tenant"
    allowed_actions:
    - "kibana_all_write"
  static: false
```

And also make the `roles_mapping` not reserved so users can assign new users to these roles:
```yaml
wazuh_ui_admin:
  reserved: false
  hidden: false
  backend_roles: []
  hosts: []
  users:
  - "wazuh_admin"
  - "kibanaserver"
  and_backend_roles: []
wazuh_ui_user:
  reserved: false
  hidden: false
  backend_roles: []
  hosts: []
  users:
  - "wazuh_user"
  - "wazuh_ro"
  and_backend_roles: []
```

Regards,
Franco Hielpos
