### ISSUE TITLE
filebeat.yml should not display the user password in plain text

### ISSUE THREAD

**Issue by s-ocando** [wazuh/wazuh-packages#1303]
|Wazuh version|Install type|Action performed|
|---|---|---|
| 4.3.0 | All-in-one | Unattended installation |

After an [unattended](https://packages-dev.wazuh.com/4.3/wazuh-install.sh) all-in-one installation, the resulting `filebeat.yml` shows the password in plain text. This should not happen as we are now using the Filebeat keystore.

```
# Wazuh - Filebeat configuration file
output.elasticsearch.hosts:
        - 127.0.0.1:9200
#        - <elasticsearch_ip_node_2>:9200 
#        - <elasticsearch_ip_node_3>:9200

output.elasticsearch:
  protocol: https
  username: ${username}
  password: f3rgv2XimlFFDnghbeXAugYxhJDwEBae
  ssl.certificate_authorities:
    - /etc/filebeat/certs/root-ca.pem
  ssl.certificate: "/etc/filebeat/certs/filebeat.pem"
  ssl.key: "/etc/filebeat/certs/filebeat-key.pem"
setup.template.json.enabled: true
setup.template.json.path: '/etc/filebeat/wazuh-template.json'
setup.template.json.name: 'wazuh'
setup.ilm.overwrite: true
setup.ilm.enabled: false

filebeat.modules:
  - module: wazuh
    alerts:
      enabled: true
    archives:
      enabled: false

logging.level: info
logging.to_files: true
logging.files:
  path: /var/log/filebeat
  name: filebeat
  keepfiles: 7
  permissions: 0644
```
