### ISSUE TITLE
Certificates creation: Problem launching `wazuh-certs-tool.sh` script

### ISSUE THREAD

**Issue by fedepacher** [wazuh/wazuh-packages#1421]
# Description

Testing the usability and user experience when generating the necessary certificates for encrypted communication between components and cluster configuration I found the following error while generating the certificates using the script `wazuh-certs-tool.sh`:

```
ERROR: The given information does not match with an IP address or a DNS.
```
# Details

|Wazuh version |Install type |Platform|
|---|---|---|
| 4.3 | Wazuh-Indexer | CentOS 8 |

# Configuration file `config.yml`

```
nodes:
  # Wazuh indexer nodes
  indexer:
    name: node-1
    ip: 172.18.1.10
    name: node-2
    ip: 172.18.1.11
    name: node-3
    ip: 172.18.1.12

  # Wazuh server nodes
  # Use node_type only with more than one Wazuh manager
  server:
    name: wazuh-1
    ip: 172.18.1.13
    node_type: master
    name: wazuh-2
    ip: 172.18.1.14
    node_type: worker

  # Wazuh dashboard nodes
  dashboard:
    name: dashboard
    ip: 172.18.1.16
```

# Steps to reproduce

- Edit the `config.yml` file to create the certificates with the `vi` editor.
- Launch the script `bash ./wazuh-certs-tool.sh -A`

### Result

```
root@centos]# bash ./wazuh-certs-tool.sh -A
29/03/2022 13:33:42 INFO: Admin certificates created.	
29/03/2022 13:33:42 ERROR: The given information does not match with an IP address or a DNS.
```

# Solution 

- Edit the `config.yml` file to create the certificates with the `nano` editor and replace CRLF with LF.

### Result

```
[root@centos]# bash ./wazuh-certs-tool.sh -A
30/03/2022 18:04:42 INFO: Admin certificates created.
30/03/2022 18:04:43 INFO: Wazuh indexer certificates created.
30/03/2022 18:04:43 INFO: Wazuh server certificates created.
30/03/2022 18:04:43 INFO: Wazuh dashboard certificates created.
```
