### ISSUE TITLE
Installation assistant does not fail with wrong `node_type` indentation issues in the `config.yml` file

### ISSUE THREAD

**Issue by DFolchA** [wazuh/wazuh-packages#1531]
|Wazuh version|Install type|Action performed|Platform|
|---|---|---|---|
| X.Y.Z-rev | Manager/API/Agent | Install/Upgrade/Remove | OS version |

If we use a config.yml like this:
```
nodes:
  indexer:
    - name: indexer
      ip: 127.0.0.1
  server:
    - name: server
      ip: 127.0.0.1
    node_type: master
    - name: server2
      ip: 127.0.0.2
    node_type: worker

  dashboard:
    - name: dashboard
      ip: 127.0.0.1
```

And generate the certificates we only the certificates for the first server node will be generated instead of failing due to an incorrect configuration.

**Comment by DFolchA** [comment]
## UPDATE

https://github.com/wazuh/wazuh-packages/commit/43cfa9869d766ff9859af71c74e06f8cc9c8d09e Added function to verify that the config file has a correct format.

**Comment by DFolchA** [comment]
## UPDATE

Test different configurations of config.yml

**Comment by miguelfdez99** [comment]
## UPDATE

- Two space indentation generates an error.

````
nodes:
  indexer:
    - name: indexer
      ip: 127.0.0.1
  server:
    - name: server
      ip: 127.0.0.1
     node_type: master
    - name: server2
      ip: 127.0.0.2
    node_type: worker

  dashboard:
    - name: dashboard
      ip: 127.0.0.1
````
````
[root@ip-172-31-8-198 ec2-user]# ./wazuh-certs-tool.sh -A
28/07/2022 09:08:54 ERROR: The configuration file /home/ec2-user/config.yml does not have a correct format.
````

- One space indentation does not generate the error though it is not correct.

````
nodes:
  indexer:
    - name: indexer
      ip: 172.31.8.198
  server:
    - name: server
      ip: 172.31.11.12
     node_type: master
    - name: server2
      ip: 172.31.33.173
     node_type: worker

  dashboard:
    - name: dashboard
      ip: 172.31.4.239
````

````
[root@ip-172-31-8-198 ec2-user]# ./wazuh-certs-tool.sh -A
28/07/2022 09:23:38 INFO: Admin certificates created.
28/07/2022 09:23:38 INFO: Wazuh indexer certificates created.
28/07/2022 09:23:39 INFO: Wazuh server certificates created.
28/07/2022 09:23:39 INFO: Wazuh dashboard certificates created.

[root@ip-172-31-8-198 ec2-user]# ls wazuh-certificates/
admin-key.pem      dashboard.pem    root-ca.key      server2.pem
admin.pem          indexer-key.pem  root-ca.pem      server-key.pem
dashboard-key.pem  indexer.pem      server2-key.pem  server.pem
````
#### Installation step by step with the previous configuration.
- Indexer

````
[root@ip-172-31-8-198 ec2-user]# curl -k -u admin:admin https://172.31.8.198:9200
{
  "name" : "indexer",
  "cluster_name" : "wazuh-cluster",
  "cluster_uuid" : "3qdfsgiRQh6XXwOct8Wacw",
  "version" : {
    "number" : "7.10.2",
    "build_type" : "rpm",
    "build_hash" : "e505b10357c03ae8d26d675172402f2f2144ef0f",
    "build_date" : "2022-01-14T03:38:06.881862Z",
    "build_snapshot" : false,
    "lucene_version" : "8.10.1",
    "minimum_wire_compatibility_version" : "6.8.0",
    "minimum_index_compatibility_version" : "6.0.0-beta1"
  },
  "tagline" : "The OpenSearch Project: https://opensearch.org/"
}
[root@ip-172-31-8-198 ec2-user]# curl -k -u admin:admin https://172.31.8.198:9200/_cat/nodes?v
ip           heap.percent ram.percent cpu load_1m load_5m load_15m node.role master name
172.31.8.198           34          60   8    0.33    0.21     0.09 dimr      *      indexer
````
- Servers

````
[root@ip-172-31-11-12 ec2-user]# /var/ossec/bin/cluster_control -l
NAME     TYPE    VERSION  ADDRESS        
server   master  4.3.6    172.31.11.12   
server2  worker  4.3.6    172.31.33.173 
````
- Dashboard

![image](https://user-images.githubusercontent.com/61159728/181479888-2765607f-5f92-4298-bb33-75613cb8b5a2.png)

![image](https://user-images.githubusercontent.com/61159728/181480007-04f11744-cc14-4787-a786-0dce64a43df9.png)

The ```config.yml``` file had an error but all the certificates create correctly and the installation also succeed.
