### ISSUE TITLE
Find out why the Indexer security initialization script can't read domain name addresses from the configuration file

### ISSUE THREAD

**Issue by javimed** [wazuh/wazuh-packages#1789]
|Wazuh version|Install type|Action performed|Platform|
|---|---|---|---|
| 4.3.6-1 | Central components | Install | CentOS 7 |

When configuring and defining the Wazuh central components nodes, if DNS names are used instead of IP addresses in the `config.yml` file...

```
nodes:
  # Wazuh indexer nodes
  indexer:
    - name: node-1
      ip: indexer01-manager.wazuh.lan
    - name: node-2
      ip: indexer02-dashboard.wazuh.lan

  # Wazuh server nodes
  # Use node_type only with more than one Wazuh manager
  server:
    - name: wazuh-1
      ip: indexer01-manager.wazuh.lan

  # Wazuh dashboard node
  dashboard:
    - name: dashboard
      ip: indexer02-dashboard.wazuh.lan
```
... as well as in the `opensearch.yml` file, then the security initialization script needs the node domain name address passed as an command line argument. For example:

`indexer-security-init.sh -ho indexer01-manager.wazuh.lan`

It would be helpful to find out why domain name addresses can't be taken from the configuration files as the input without requiring to use the `-ho` parameter when executing the command.
