### ISSUE TITLE
Certificate generation issue with DNS names with single characters

### ISSUE THREAD

**Issue by DeadManZim** [wazuh/wazuh-packages#1858]
|Wazuh version|Install type|Action performed|Platform|
|---|---|---|---|
| 4.3 | Manager | Install | Ubuntu 20.04 |

We have recently had an issue trying to use DNS names instead of IP addresses when setting up a Wazuh cluster. 
Every time we ran the tool we were getting the  "The given information does not match with an IP address or a DNS." error.
After some digging and help from a developer friend, we found the cause in the regex in the script that checks if the DNS is valid. 
It turns out that the regex cannot validate single character subdomains.
E.g. [somewhere.domain.com](http://somewhere.domain.com/) will work, while [somewhere.x.domain.com](http://somewhere.x.domain.com/) will fail.

The offending line in the script is:
`isDNS=$(echo "${2}" | grep -P "^[a-zA-Z0-9][a-zA-Z0-9-]{1,61}[a-zA-Z0-9](?:\.[a-zA-Z-]{2,})+$" )`

We fixed this by using the following regex:
`^(([a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9\-]*[a-zA-Z0-9])\.)*([A-Za-z0-9]|[A-Za-z0-9][A-Za-z0-9\-]*[A-Za-z0-9])$`

**To reproduce:**

Config.yml that will fail:

```yaml
nodes:
  # Wazuh indexer nodes
  indexer:
    - name: wazin1
      ip: wazin1.z.lan
    - name: wazin2
      ip: wazin2.z.lan
    - name: wazin3
      ip: wazin3.z.lan

  # Wazuh server nodes
  # Use node_type only with more than one Wazuh manager
  server:
    - name: wazman1
      ip: wazman1.z.lan
     node_type: master
    - name: wazman2
      ip: wazman2.z.lan
     node_type: worker

  # Wazuh dashboard nodes
  dashboard:
    - name: wazdash
      ip: wazdash.z.lan
```

Config.yml that will work:

```yaml
nodes:
  # Wazuh indexer nodes
  indexer:
    - name: wazin1
      ip: wazin1.zee.lan
    - name: wazin2
      ip: wazin2.zee.lan
    - name: wazin3
      ip: wazin3.zee.lan

  # Wazuh server nodes
  # Use node_type only with more than one Wazuh manager
  server:
    - name: wazman1
      ip: wazman1.zee.lan
     node_type: master
    - name: wazman2
      ip: wazman2.zee.lan
     node_type: worker

  # Wazuh dashboard nodes
  dashboard:
    - name: wazdash
      ip: wazdash.zee.lan
```

**Comment by DeadManZim** [comment]
To clarify: The issue is present in both the wazuh-install.sh file (search for the word information) and the wazuh-certs-tool.sh file.

**Comment by DeadManZim** [comment]
Line 3051 in wazuh-install.sh and line 102 in the wazuh-certs-tool.sh.

**Comment by davidcr01** [comment]
The DNS validation was improved in this PR: https://github.com/wazuh/wazuh-packages/pull/2381

**Comment by davidcr01** [comment]
## Update Report

The DNS validation was improved in this PR: https://github.com/wazuh/wazuh-packages/pull/2381

After checking the regex of the DNS validation, currently, the DNS specified is valid:
![image](https://github.com/wazuh/wazuh-packages/assets/72193239/e43173ab-95b6-480b-8179-4b88c506deaf)

To ensure that the issue is solved, a test has been performed to check if the certificates are generated correctly, using the `config.yml` file provided in the issue:
```YAML
nodes:
  # Wazuh indexer nodes
  indexer:
    - name: wazin1
      ip: wazin1.z.lan
    - name: wazin2
      ip: wazin2.z.lan
    - name: wazin3
      ip: wazin3.z.lan

  # Wazuh server nodes
  # Use node_type only with more than one Wazuh manager
  server:
    - name: wazman1
      ip: wazman1.z.lan
     node_type: master
    - name: wazman2
      ip: wazman2.z.lan
     node_type: worker

  # Wazuh dashboard nodes
  dashboard:
    - name: wazdash
      ip: wazdash.z.lan
```

```console
davidcr01:~/Wazuh/wazuh-packages/unattended_installer(master)$ sudo bash wazuh-install.sh -g -i
30/08/2023 13:17:35 INFO: Starting Wazuh installation assistant. Wazuh version: 4.8.0
30/08/2023 13:17:35 INFO: Verbose logging redirected to /var/log/wazuh-install.log
30/08/2023 13:17:44 WARNING: Hardware and system checks ignored.
30/08/2023 13:17:44 INFO: --- Configuration files ---
30/08/2023 13:17:44 INFO: Generating configuration files.
30/08/2023 13:17:46 INFO: Created wazuh-install-files.tar. It contains the Wazuh cluster key, certificates, and passwords necessary for installation.
```

## Conclusion

The DNS regex was improved in 4.8.0 and this issue is solved. No further changes are necessary.
