### ISSUE TITLE
The `config.yml` template comments need to be improved to avoid indentation failures

### ISSUE THREAD

**Issue by alberpilot** [wazuh/wazuh-packages#1860]
A community user[ had a problem](https://wazuh.slack.com/archives/C0A933R8E/p1664190144769509) using the `config.yml` template, as the example used [here](https://documentation.wazuh.com/current/user-manual/certificates.html) could mislead due to amount of characters to remove when using a distributed configuration. Example:

```
  server:
    - name: wazuh-1
      ip: <wazuh-manager-ip>
    # node_type: master
    # - name: wazuh-2
    #   ip: <wazuh-manager-ip>
    # node_type: worker
```

If a user removes the `#` character and one blank space, this is the result:
```
  server:
    - name: wazuh-1
      ip: <wazuh-manager-ip>
    node_type: master
    - name: wazuh-2
      ip: <wazuh-manager-ip>
    node_type: worker
```
`node_type` is now un-indented, which will produce problems generating certificates. 

## Tasks
- [ ] The `config.yml` template needs to be reviewed in order to find a more straightforward out-of-error format. 
- [ ] Determine if wazuh-ansible/docker/puppet etc needs to propagate the change. 
- [ ] wazuh-documentation PR changing the template. 
- [ ] Apply changes in production. 

# Stages (Updated)
Due to important cascade changes, it's better to split this issue into two jobs:
The tasks are still the same, but the changes should affect only to commented lines. Improving the user experience when removing those comments avoiding indentation errors. 

Changes described in comments like https://github.com/wazuh/wazuh-packages/issues/1860#issuecomment-1285030675 and https://github.com/wazuh/wazuh-packages/issues/1860#issuecomment-1290059536 will be completed in a new issue: https://github.com/wazuh/wazuh-packages/issues/1920

**Comment by davidjiglesias** [comment]
I would like to suggest a few other improvements to ease the user's understanding of the different modules:

From current:

```
nodes:
  # Wazuh indexer nodes
  indexer:
    - name: node-1
      ip: <indexer-node-ip>
  # Wazuh server nodes
  # Use node_type only with more than one Wazuh manager
  server:
    - name: wazuh-1
      ip: <wazuh-manager-ip>
  # Wazuh dashboard node
  dashboard:
    - name: dashboard
      ip: <dashboard-node-ip>
```
