### ISSUE TITLE
Installing the Wazuh indexer using the assistant never ends if the configuration file has commentaries

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh-packages#1959]
|Wazuh version|Install type|Install method|Platform|
|---|---|---|---|
| 4.4.0-1  | Assistance | Package | Amazon Linux 2 |

### Description

Wazuh cluster key generation never ends if we use a configuration file with commentaries. 
Detected by @juliamagan 

<details>

<summary> Wazuh install output  </summary>

```
[root@ip-172-31-21-211 ec2-user]# bash wazuh-install.sh --generate-config-files
30/11/2022 15:57:25 INFO: Starting Wazuh installation assistant. Wazuh version: 4.4.0
30/11/2022 15:57:25 INFO: Verbose logging redirected to /var/log/wazuh-install.log
30/11/2022 15:57:26 INFO: --- Configuration files ---
30/11/2022 15:57:26 INFO: Generating configuration files.
```

</details>

<details>

<summary> config.yaml </summary>

```
nodes:
  # Wazuh indexer nodes
  indexer:
    - name: indexer-1
      ip: <indexer-node-ip>
        #- name: indexer-2
        #ip: <indexer-node-ip>
        #- name: indexer-3
        #ip: <indexer-node-ip>
  server:
    - name: server-1
      ip: <server-node-ip>
      node_type: master
        #- name: server-2
        #ip: <server-node-ip>
        #node_type: worker
        #- name: server-3
        #ip: <server-node-ip>
        #node_type: worker
  dashboard:
    - name: dashboard-1
      ip: <dashboard-node-ip>
        #- name: dashboard-2
        #ip: <dashboard-node-ip>
        #- name: dashboard-3
        #ip: <dashboard-node-ip>
```

</details>

### How to reproduce
- Get wazuh-install script: `curl -sO https://packages-dev.wazuh.com/4.4/wazuh-install.sh`
- Get specified `config.yml` file
- Generate config files: `bash wazuh-install.sh --generate-config-files`

**Comment by verdx** [comment]
There are two errors possible, one for the lack of valid IPs and one for an unnecessary `node_type`. If only one of those errors is present, a correct log is shown, but when both of them are there the script enters the loop.

With a new test, changing the script to parse the Yaml just once, it is seen there is no loop, it just took a lot of time and each one of the errors `awk: cmd. line:11: (FILENAME=- FNR=26) fatal: r_interpret: t1->stptr: can't allocate 889552896 bytes of memory (Cannot allocate memory)` is a time the Yaml parser function is called:

<details> 

```
[vagrant@amazonlinux2 ~]$ sudo bash wazuh-install.sh --generate-config-files --verbose
13/12/2022 10:15:47 INFO: Starting Wazuh installation assistant. Wazuh version: 4.4.0
13/12/2022 10:15:47 INFO: Verbose logging redirected to /var/log/wazuh-install.log
13/12/2022 10:15:51 INFO: --- Configuration files ---
13/12/2022 10:15:51 INFO: Generating configuration files.
awk: cmd. line:11: (FILENAME=- FNR=26) fatal: r_interpret: t1->stptr: can't allocate 881561596 bytes of memory (Cannot allocate memory)
nodes_indexer_1="indexer-1" nodes_indexer_1_ip="<indexer-node-ip" nodes_server_1="server-1" nodes_server_1_ip="<server-node-ip" nodes_server_1_node_type="master" nodes_dashboard_1="dashboard-1" nodes_dashboard_=" nodes_dashboard_1" nodes_indexer_1_=" nodes_indexer_1_ip" nodes_=" nodes_indexer nodes_server nodes_dashboard" nodes_server_1_=" nodes_server_1_ip nodes_server_1_node_type" nodes_indexer_=" nodes_indexer_1" __=" nodes" nodes_server_=" nodes_server_1"
wazuh-install.sh: eval: line 3271: syntax error near unexpected token `|'
wazuh-install.sh: eval: line 3271: `nodes_server_=" nodes_server_1" | grep -E nodes[_]+indexer[_]+[0-9]+= | cut -d = -f 2 ) )'
wazuh-install.sh: eval: line 3272: syntax error near unexpected token `|'
wazuh-install.sh: eval: line 3272: `nodes_server_=" nodes_server_1" | grep -E nodes[_]+server[_]+[0-9]+= | cut -d = -f 2 ) )'
wazuh-install.sh: eval: line 3273: syntax error near unexpected token `|'
wazuh-install.sh: eval: line 3273: `nodes_server_=" nodes_server_1" | grep -E nodes[_]+dashboard[_]+[0-9]+= | cut -d = -f 2) )'
wazuh-install.sh: eval: line 3274: syntax error near unexpected token `|'
wazuh-install.sh: eval: line 3274: `nodes_server_=" nodes_server_1" | grep -E nodes[_]+indexer[_]+[0-9]+[_]+ip= | cut -d = -f 2) )'
wazuh-install.sh: eval: line 3275: syntax error near unexpected token `|'
wazuh-install.sh: eval: line 3275: `nodes_server_=" nodes_server_1" | grep -E nodes[_]+server[_]+[0-9]+[_]+ip= | cut -d = -f 2) )'
wazuh-install.sh: eval: line 3276: syntax error near unexpected token `|'
wazuh-install.sh: eval: line 3276: `nodes_server_=" nodes_server_1" | grep -E nodes[_]+dashboard[_]+[0-9]+[_]+ip= | cut -d = -f 2 ) )'
wazuh-install.sh: eval: line 3277: syntax error near unexpected token `|'
wazuh-install.sh: eval: line 3277: `nodes_server_=" nodes_server_1" | grep -E nodes[_]+server[_]+[0-9]+[_]+node_type= | cut -d = -f 2 ) )'
wazuh-install.sh: eval: line 3278: syntax error near unexpected token `|'
wazuh-install.sh: eval: line 3278: `nodes_server_=" nodes_server_1" | grep -o -E 'nodes[_]+server[_]+[0-9]+[_]+ip' | sort -u | wc -l) )'
seq: invalid floating point argument: 
Try 'seq --help' for more information.
13/12/2022 10:16:30 DEBUG: Creating the root certificate.
Generating a 2048 bit RSA private key
...............+++
.............................................................+++
writing new private key to '/tmp/wazuh-certificates//root-ca.key'
-----
Generating RSA private key, 2048 bit long modulus
........................................................................................................+++
.............+++
e is 65537 (0x10001)
Signature ok
subject=/C=US/L=California/O=Wazuh/OU=Wazuh/CN=admin
Getting CA Private Key
13/12/2022 10:16:31 DEBUG: Generating random passwords.
13/12/2022 10:16:31 INFO: Created wazuh-install-files.tar. It contains the Wazuh cluster key, certificates, and passwords necessary for installation.
[vagrant@amazonlinux2 ~]$ 
```
</details>

When letting it run, even with all the errors in `config.yml`,  the error of the node type still appears, there is no loop or freezing of the script, but the continuous errors of awk and the fact they take a lot of time between them makes it seem as if it is stuck. 

The script has been improved so that function `cert_parseYaml` is only called once, and a new error has been added so that incorrect ips are detected, as seen here:

<details>

```
[root@amazonlinux2 vagrant]# cat config.yml
nodes:
  # Wazuh indexer nodes
  indexer:
    - name: indexer-1
      ip: <indexer-node-ip>
        #- name: indexer-2
        #ip: <indexer-node-ip>
        #- name: indexer-3
        #ip: <indexer-node-ip>
  server:
    - name: server-1
      ip: <server-node-ip>
      node_type: master
        #- name: server-2
        #ip: <server-node-ip>
        #node_type: worker
        #- name: server-3
        #ip: <server-node-ip>
        #node_type: worker
  dashboard:
    - name: dashboard-1
      ip: <dashboard-node-ip>
        #- name: dashboard-2
        #ip: <dashboard-node-ip>
        #- name: dashboard-3
        #ip: <dashboard-node-ip>
[root@amazonlinux2 vagrant]# bash wazuh-install.sh --generate-config-files
13/12/2022 16:29:49 INFO: Starting Wazuh installation assistant. Wazuh version: 4.4.0
13/12/2022 16:29:49 INFO: Verbose logging redirected to /var/log/wazuh-install.log
13/12/2022 16:29:53 INFO: --- Configuration files ---
13/12/2022 16:29:53 INFO: Generating configuration files.
 awk: cmd. line:11: (FILENAME=- FNR=26) fatal: r_interpret: t1->stptr: can't allocate 879939571 bytes of memory (Cannot allocate memory)
13/12/2022 16:30:33 ERROR: Invalid IP address: <indexer-node-ip
[root@amazonlinux2 vagrant]#  
```
</details>

After more research, and being solved the timing issues, only thing to correct is the error from awk.
- The error is ` awk: cmd. line:11: (FILENAME=- FNR=26) fatal: r_interpret: t1->stptr: can't allocate 879939571 bytes of memory (Cannot allocate memory)` 
- It doesn't stop the script and doesn't happen when the config file is correctly filled.
- The only consequence seen is the last line is not accepted, and so the dashboard IP is not parsed, as seen running the awk command separately:
<details>

```
[root@amazonlinux2 vagrant]# awk $'-F\034' '{multi=0;
        if(match($0,/[ \t]*\|[ \t]*$/)){multi=1; sub(/[ \t]*\|[ \t]*$/,"");}
        if(match($0,/[ \t]*>[ \t]*$/)){multi=2; sub(/[ \t]*>[ \t]*$/,"");}
        while(multi>0){
            str=$0; gsub(/^[ \t]*/,"", str);
            indent=index($0,str);
            indentstr=substr($0, 0, indent+-1) "  ";
            obuf=$0;
            getline;
            while(index($0,indentstr)){
                obuf=obuf substr($0, length(indentstr)+1);
                if (multi==1){obuf=obuf "\\n";}
                if (multi==2){
                    if(match($0,/^[ \t]*$/))
                        obuf=obuf "\\n";
                        else obuf=obuf " ";
                }
                getline;
            }
            sub(/[ \t]*$/,"",obuf);
            print obuf;
            multi=0;
            if(match($0,/[ \t]*\|[ \t]*$/)){multi=1; sub(/[ \t]*\|[ \t]*$/,"");}
            if(match($0,/[ \t]*>[ \t]*$/)){multi=2; sub(/[ \t]*>[ \t]*$/,"");}
        }
print}' config.yml
nodes:
  # Wazuh indexer nodes
  indexer:
    - name: indexer-1
      ip: <indexer-node-ip#- name: indexer-2 #ip: <indexer-node-ip> #- name: indexer-3 #ip: <indexer-node-ip>
  server:
    - name: server-1
      ip: <server-node-ip
      node_type: master
        #- name: server-2
        #ip: <server-node-ip
        #node_type: worker
        #- name: server-3
        #ip: <server-node-ip
        #node_type: worker
  dashboard:
    - name: dashboard-1
awk: cmd. line:11: (FILENAME=config.yml FNR=26) fatal: r_interpret: t1->stptr: can't allocate 884379646 bytes of memory (Cannot allocate memory)
[root@amazonlinux2 vagrant]# 
```
</details>

Symbol `>` is part of the Yaml syntax and is a symbol to fold a newline:
```
Block scalars are delimited with indentation with optional modifiers to preserve (|) or fold (>) newlines.
```
The parser, being a general Yaml parser, removes the next newline whenever this symbol appears and instead writes `""`. This removes the EOF symbol in the last line, creating an infinite loop in `awk` looking for it. 

When the IPs are surrounded by double-quotes,`awk` does not give an error, and this change will be introduced in PR #1981, solving this error.

PRs to close this issue:
- [ ] #1981 
- [ ]
