### ISSUE TITLE
Installation assistant 4.6 `Cannot install dependency: coreutils`

### ISSUE THREAD

**Issue by javimed** [wazuh/wazuh-packages#2430]
|Wazuh version|Install type|Action performed|Platform|
|---|---|---|---|
| 4.6.0-alpha1 | Installation assistant | Install | Amazon Linux 2023 |

```
$ docker run -it amazonlinux:2023 /bin/bash
```

```
bash-5.2# curl -sO https://packages-dev.wazuh.com/4.6/wazuh-install.sh
bash-5.2# curl -sO https://packages-dev.wazuh.com/4.6/config.yml
```

```
bash-5.2# cat ./config.yml 
nodes:
  # Wazuh indexer nodes
  indexer:
    - name: node-1
      ip: 172.17.0.2
    - name: node-2
      ip: 172.17.0.3
    #- name: node-3
    #  ip: <indexer-node-ip>

  # Wazuh server nodes
  # If there is more than one Wazuh server
  # node, each one must have a node_type
  server:
    - name: wazuh-1
      ip: 172.17.0.4
    #  node_type: master
    #- name: wazuh-2
    #  ip: <wazuh-manager-ip>
    #  node_type: worker
    #- name: wazuh-3
    #  ip: <wazuh-manager-ip>
    #  node_type: worker

  # Wazuh dashboard nodes
  dashboard:
    - name: dashboard
      ip: 172.17.0.4
```

```
bash-5.2# bash wazuh-install.sh --generate-config-files
07/09/2023 13:45:54 INFO: Starting Wazuh installation assistant. Wazuh version: 4.6.0
07/09/2023 13:45:54 INFO: Verbose logging redirected to /var/log/wazuh-install.log
07/09/2023 13:45:56 INFO: --- Dependencies ---
07/09/2023 13:45:56 INFO: Installing systemd.
07/09/2023 13:46:09 INFO: Installing tar.
07/09/2023 13:46:12 INFO: Installing coreutils.
07/09/2023 13:46:13 ERROR: Cannot install dependency: coreutils.
bash-5.2#
```

```
bash-5.2# cat /var/log/wazuh-install.log
07/09/2023 13:48:26 INFO: Starting Wazuh installation assistant. Wazuh version: 4.6.0
07/09/2023 13:48:26 INFO: Verbose logging redirected to /var/log/wazuh-install.log
07/09/2023 13:48:28 INFO: --- Dependencies ---
07/09/2023 13:48:28 INFO: Installing coreutils.
Last metadata expiration check: 0:26:18 ago on Thu Sep  7 13:22:10 2023.
Error: 
 Problem: problem with installed package coreutils-single-8.32-30.amzn2023.0.3.x86_64
  - package coreutils-8.32-30.amzn2023.0.3.x86_64 conflicts with coreutils-single provided by coreutils-single-8.32-30.amzn2023.0.3.x86_64
  - conflicting requests
(try to add '--allowerasing' to command line to replace conflicting packages or '--skip-broken' to skip uninstallable packages)
07/09/2023 13:48:28 ERROR: Cannot install dependency: coreutils.
bash-5.2# 

```
