### ISSUE TITLE
Message error generating the Wazuh certificates

### ISSUE THREAD

**Issue by rauldpm** [wazuh/wazuh-packages#2524]
## Description

To test the [OpenSearch bump to 2.10.0](https://github.com/wazuh/wazuh-packages/issues/2520), it is necessary to generate the certificates with the 4.8.0 (master) branch, but an error due to the redirection is obtained, which tries to create a directory

```
[root@centos7 vagrant]# bash ./wazuh-certs-tool.sh -A
mkdir: cannot create directory ‘>> /dev/null 2>&1’: No such file or directory
11/10/2023 20:38:34 INFO: Admin certificates created.
11/10/2023 20:38:34 INFO: Wazuh indexer certificates created.
```

Configuration file used:

```
[root@centos7 vagrant]# cat config.yml 
nodes:
  # Wazuh indexer nodes
  indexer:
    - name: indexer-1
      ip: "192.168.56.4"
```

The certificates appear to be created correctly

```
[root@centos7 vagrant]# ls wazuh-certificates/
admin-key.pem  admin.pem  indexer-1-key.pem  indexer-1.pem  root-ca.key  root-ca.pem
```

## Tasks

- [ ] Apply the necessary changes to correctly create the certificates

## Validation

- [ ] Certificates are created successfully without error messages
