### ISSUE TITLE
[ISM rollover] Create new role to grant ISM API permissions

### ISSUE THREAD

**Issue by AlexRuiz7** [wazuh/wazuh-packages#2552]
### Description

As part of https://github.com/wazuh/wazuh/issues/18999, we need to create a new role in the indexer to grant ISM API permissions, so the app can upload the ISM policy for auto-rollover. This role can be used by the users and wazuh-cloud for their own needs.

The details about the role is described in the [main issue](https://github.com/wazuh/wazuh/issues/18999#issuecomment-1775547380).

----

[action_groups.yml](https://opensearch.org/docs/latest/security/configuration/yaml/#action_groupsyml)

```yml
---
manage_ism:
  reserved: true
  hidden: false
  allowed_actions:
  - "cluster:admin/opendistro/ism/*"
  static: false
```

[roles.yml](https://opensearch.org/docs/latest/security/configuration/yaml/#rolesyml)

```yml
---
manage_ism:
  reserved: true
  hidden: false
  cluster_permissions:
  - "manage_ism"
  static: false
```

[roles_mapping.yml](https://opensearch.org/docs/latest/security/configuration/yaml/#roles_mappingyml)

```yml
---
manage_ism:
  reserved: true
  hidden: false
  users:
  - "kibanaserver"
```

_Originally posted by @AlexRuiz7 in https://github.com/wazuh/wazuh/issues/18999#issuecomment-1775547380_
