### ISSUE TITLE
[Development] 4.2 package changes permissions of root directory in Oracle Linux 7.8

### ISSUE THREAD

**Issue by DFolchA** [wazuh/wazuh-packages#822]
|Wazuh version|Install type|Action performed|Platform|
|---|---|---|---|
| 4.2.0-40208| Manager/Agent | Install/Upgrade/Remove | Oracle Linux 7.8|

We were notified that in Oracle Linux 7.8 when upgrading from 4.0.4 the 4.2.0 package changes the permissions of `/` and `/etc`to `root:ossec`.

Packages:
- https://s3.us-west-1.amazonaws.com/packages-dev.wazuh.com/custom/4.2-rc-rcs-wp/wazuh-agent-4.2.0-0.5.x86_64.rpm
- https://s3.us-west-1.amazonaws.com/packages-dev.wazuh.com/custom/4.2-rc-rcs-wp/wazuh-manager-4.2.0-0.5.x86_64.rpm

**Comment by DFolchA** [comment]
## Update

### Deployed system

![imagen](https://user-images.githubusercontent.com/19505384/126451780-447b0c7d-d267-4ef4-bfb2-1aaaeb0159a2.png)


### New installation Wazuh stopped

![imagen](https://user-images.githubusercontent.com/19505384/126450659-5a387f75-a2a4-4f42-ac7b-25a712ed63c8.png)

### New installation Wazuh running

![imagen](https://user-images.githubusercontent.com/19505384/126451557-5acdc819-e123-4440-b721-abbd80d8a781.png)

On a new installation, the permissions of `/` and `/etc` have not changed.

**Comment by DFolchA** [comment]
## Update upgrade from 4.0.4

### Wazuh 4.0.4 installation

![imagen](https://user-images.githubusercontent.com/19505384/126455613-91c26191-a47d-485c-af4b-99617b91b1e6.png)

### Wazuh 4.2.0 upgrade using yum

![imagen](https://user-images.githubusercontent.com/19505384/126463249-f5293098-00bb-4438-b202-53c422a67944.png)

**Comment by DFolchA** [comment]
## Update: Install and upgrade using ansible

As reported the error appeared when using Ansible to deploy Wazuh to be as close as possible to the reports I wrote a couple of Ansible playbooks that install and configure Wazuh:

### 4.2.0 Installation

**Playbook**
```
- hosts: managers
  become: true
  tasks:
    - name: Download package
      command: wget -P /home https://s3.us-west-1.amazonaws.com/packages-dev.wazuh.com/custom/4.2-rc-rcs-wp/wazuh-manager-4.2.0-0.5.x86_64.rpm
      
    - name: Install wazuh
      command: rpm -i /home/wazuh-manager-4.2.0-0.5.x86_64.rpm

    - name: Start Wazuh
      command: systemctl start wazuh-manager

    - name: Check permissions 
      find:
        paths: /
        file_type: any
      register: perm

    - debug:
       var: perm

- hosts: agents
  become: true
  tasks:
    - name: Download package
      command: wget -P /home https://s3.us-west-1.amazonaws.com/packages-dev.wazuh.com/custom/4.2-rc-rcs-wp/wazuh-agent-4.2.0-0.5.x86_64.rpm
      
    - name: Install wazuh
      command: rpm -i /home/wazuh-agent-4.2.0-0.5.x86_64.rpm

    - name: Set manager IP
      replace:
        path: /opt/ossec/etc/ossec.conf
        regexp: 'MANAGER_IP'
        replace: '172.16.1.55'
        backup: yes

    - name: Start Wazuh
      command: systemctl start wazuh-agent

    - name: Check permissions 
      find:
        paths: /
        file_type: any
      register: perm

    - debug:
       var: perm
```

Results: [install_result.txt](https://github.com/wazuh/wazuh-packages/files/6855157/install_result.txt)

**Manager**
```
            {
                "atime": 1626866223.9691598, 
                "ctime": 1626866214.847094, 
                "dev": 64512, 
                "gid": 0, 
                "gr_name": "root", 
                "inode": 67108993, 
                "isblk": false, 
                "ischr": false, 
                "isdir": true, 
                "isfifo": false, 
                "isgid": false, 
                "islnk": false, 
                "isreg": false, 
                "issock": false, 
                "isuid": false, 
                "mode": "0755", 
                "mtime": 1626866214.847094, 
                "nlink": 75, 
                "path": "/etc", 
                "pw_name": "root", 
                "rgrp": true, 
                "roth": true, 
                "rusr": true, 
                "size": 8192, 
                "uid": 0, 
                "wgrp": false, 
                "woth": false, 
                "wusr": true, 
                "xgrp": true, 
                "xoth": true, 
                "xusr": true
            },
``` 

**Agent**
```
        {
            "atime": 1626866271.5538943, 
            "ctime": 1626866267.0318599, 
            "dev": 64512, 
            "gid": 0, 
            "gr_name": "root", 
            "inode": 67108993, 
            "isblk": false, 
            "ischr": false, 
            "isdir": true, 
            "isfifo": false, 
            "isgid": false, 
            "islnk": false, 
            "isreg": false, 
            "issock": false, 
            "isuid": false, 
            "mode": "0755", 
            "mtime": 1626866267.0318599, 
            "nlink": 75, 
            "path": "/etc", 
            "pw_name": "root", 
            "rgrp": true, 
            "roth": true, 
            "rusr": true, 
            "size": 8192, 
            "uid": 0, 
            "wgrp": false, 
            "woth": false, 
            "wusr": true, 
            "xgrp": true, 
            "xoth": true, 
            "xusr": true
        }, 
``` 


### Udate Wazuh

**Playbook**
```
- hosts: managers
  become: true
  tasks:
  
    - name: Download package
      command: wget -P /home https://s3.us-west-1.amazonaws.com/packages-dev.wazuh.com/trash/yum/wazuh-manager-4.0.4-1.x86_64.rpm
      
    - name: Install wazuh
      command: rpm -i /home/wazuh-manager-4.0.4-1.x86_64.rpm

    - name: Start Wazuh
      command: systemctl start wazuh-manager

    - name: Download package
      command: wget -P /home https://s3.us-west-1.amazonaws.com/packages-dev.wazuh.com/custom/4.2-rc-rcs-wp/wazuh-manager-4.2.0-0.5.x86_64.rpm
      
    - name: Upgrade wazuh
      command: rpm -U /home/wazuh-manager-4.2.0-0.5.x86_64.rpm

    - name: Check permissions 
      find:
        paths: /
        file_type: any
      register: perm

    - debug:
       var: perm

- hosts: agents
  become: true
  tasks:
    - name: Download package
      command: wget -P /home https://s3.us-west-1.amazonaws.com/packages-dev.wazuh.com/trash/yum/wazuh-agent-4.0.4-1.x86_64.rpm
      
    - name: Install wazuh
      command: rpm -i /home/wazuh-agent-4.0.4-1.x86_64.rpm

    - name: Set manager IP
      replace:
        path: /opt/ossec/etc/ossec.conf
        regexp: 'MANAGER_IP'
        replace: '172.16.1.55'
        backup: yes

    - name: Start Wazuh
      command: systemctl start wazuh-agent

    - name: Download package
      command: wget -P /home https://s3.us-west-1.amazonaws.com/packages-dev.wazuh.com/custom/4.2-rc-rcs-wp/wazuh-agent-4.2.0-0.5.x86_64.rpm
      
    - name:  wazuh
      command: rpm -U /home/wazuh-agent-4.2.0-0.5.x86_64.rpm

    - name: Check permissions 
      find:
        paths: /
        file_type: any
      register: perm

    - debug:
       var: perm
```

**Results:** [update_result.txt](https://github.com/wazuh/wazuh-packages/files/6855129/update_result.txt)

**Manager:**
```
        {
            "atime": 1626865472.4865825, 
            "ctime": 1626865559.0542324, 
            "dev": 64512, 
            "gid": 0, 
            "gr_name": "root", 
            "inode": 67108993, 
            "isblk": false, 
            "ischr": false, 
            "isdir": true, 
            "isfifo": false, 
            "isgid": false, 
            "islnk": false, 
            "isreg": false, 
            "issock": false, 
            "isuid": false, 
            "mode": "0755", 
            "mtime": 1626865559.0542324, 
            "nlink": 75, 
            "path": "/etc", 
            "pw_name": "root", 
            "rgrp": true, 
            "roth": true, 
            "rusr": true, 
            "size": 8192, 
            "uid": 0, 
            "wgrp": false, 
            "woth": false, 
            "wusr": true, 
            "xgrp": true, 
            "xoth": true, 
            "xusr": true
        }, 
```
**Agent**

```
        {
            "atime": 1626865645.1739259, 
            "ctime": 1626865647.772947, 
            "dev": 64512, 
            "gid": 0, 
            "gr_name": "root", 
            "inode": 67108993, 
            "isblk": false, 
            "ischr": false, 
            "isdir": true, 
            "isfifo": false, 
            "isgid": false, 
            "islnk": false, 
            "isreg": false, 
            "issock": false, 
            "isuid": false, 
            "mode": "0755", 
            "mtime": 1626865647.772947, 
            "nlink": 75, 
            "path": "/etc", 
            "pw_name": "root", 
            "rgrp": true, 
            "roth": true, 
            "rusr": true, 
            "size": 8192, 
            "uid": 0, 
            "wgrp": false, 
            "woth": false, 
            "wusr": true, 
            "xgrp": true, 
            "xoth": true, 
            "xusr": true
        },
```

There are no permission changes in `/etc`

Additionally, I also wrote a couple of playbooks to uninstall Wazuh and to check the permissions:

```
- hosts: managers
  become: true
  tasks:

    - name: Uninstall wazuh
      command: rpm -e wazuh-manager

    - name: Remove file
      command: rm -f /home/wazuh-manager-4.2.0-0.5.x86_64.rpm

    - name: remove dir
      command: rm -rf /opt/ossec

- hosts: agents
  become: true
  tasks:
    - name: Uninstall wazuh
      command: rpm -e wazuh-agent

    - name: Remove file
      command: rm -f /home/wazuh-agent-4.2.0-0.5.x86_64.rpm

    - name: remove dir
      command: rm -rf /opt/ossec

```

```
- hosts: managers
  become: true
  tasks:
    - name: Check permissions 
      find:
        paths: /
        file_type: any
      register: perm

    - debug:
       var: perm

- hosts: agents
  become: true
  tasks:
    - name: Check permissions 
      find:
        paths: /
        file_type: any
      register: perm

    - debug:
       var: perm
```

**Comment by DFolchA** [comment]
## Update: Check package SPEC with rpmrebuild

I have extracted the SPEC from the package with rpmrebuild and verified that it contains the same installation scripts as the one in the repository, and defines the same files.

[agent.spec.txt](https://github.com/wazuh/wazuh-packages/files/6855445/agent.spec.txt)

**Comment by DFolchA** [comment]
## Update: Modified playbooks

I have modified the playbook that checks the permissions so it fails if it finds a file or directory inside `/` with group or user `ossec`.

```
- hosts: managers
  become: true
  tasks:
    - name: Check permissions 
      find:
        paths: /
        file_type: any
      register: perm

    - name: verify perms user not ossec
      fail: 
        msg: "Wrong user or group"
      when: item.gr_name == "ossec" or item.pw_name == "ossec"
      with_items: 
        - "{{ perm.files }}"
      
- hosts: agents
  become: true
  tasks:
    - name: Check permissions 
      find:
        paths: /
        file_type: any
      register: perm

    - name: verify perms user not ossec
      fail: 
        msg: "Wrong user or group"
      when: item.gr_name == "ossec" or item.pw_name == "ossec"
      with_items: 
        - "{{ perm.files }}"

```
